### ISSUE TITLE
Text/Article project description

### ISSUE THREAD

**Issue by Malthael134** [KWR-Informatik-AG/documentation#3]
[https://github.com/KWR-Informatik-AG/documentation/blob/main/docs/projekte/werwolf-webapp/index.md](https://github.com/KWR-Informatik-AG/documentation/blob/main/docs/projekte/werwolf-webapp/index.md)
Text noch sehr ausbaufähig in vielen Bereichen (Grammatik, Rechtschreibung, Textstruktur). Bitte verbessern @Jolomolokolo.

**Comment by Jolomolokolo** [comment]
1. Sehr grobe erste Rohfassung
2. DU HAST SCHULE, DU SOLLTEST KEINE ISSUES GRADE ERSTELLEN KÖNNEN
3. Überarbeitung ist in Arbeit
